apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-rollouts
  labels:
    app.kubernetes.io/component: rollouts-controller
    app.kubernetes.io/name: argo-rollouts
    app.kubernetes.io/part-of: argo-rollouts
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argo-rollouts
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argo-rollouts
    spec:
      serviceAccountName: argo-rollouts
      containers:
      - command:
        - "/bin/rollouts-controller"
        image: argoproj/argo-rollouts:latest
        imagePullPolicy: Always
        name: argo-rollouts
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      securityContext:
        runAsNonRoot: true
      volumes:
      - name: tmp
        emptyDir: {}
  strategy:
    type: Recreate
