apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- argo-rollouts-sa.yaml
- argo-rollouts-deployment.yaml
- argo-rollouts-aggregate-roles.yaml
- argo-rollouts-metrics-service.yaml
- argo-rollouts-notification-secret.yaml
images:
- name: quay.io/codefresh/argo-rollouts
  newTag: latest
