resources:
- argo-rollouts-sa.yaml
- argo-rollouts-role.yaml
- argo-rollouts-rolebinding.yaml
- argo-rollouts-deployment.yaml
- argo-rollouts-aggregate-roles.yaml

imageTags:
- name: argoproj/rollout-controlller
  newTag: v0.1.0 
