required = [
    "k8s.io/code-generator/cmd/client-gen",
    "github.com/emicklei/go-restful",
    "github.com/go-openapi/spec",
    "k8s.io/kube-openapi/cmd/openapi-gen",
]

[[constraint]]
  name = "k8s.io/client-go"
  branch = "release-14.0"

[[constraint]]
  name = "istio.io/client-go"
  branch = "release-1.4"

[[constraint]]
  name = "k8s.io/code-generator"
  branch = "release-1.17"

[[constraint]]
  branch = "release-1.17"
  name = "k8s.io/api"

[[constraint]]
  name = "k8s.io/apiserver"
  branch = "release-1.17"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.17"

[[constraint]]
  name = "k8s.io/kubernetes"
  branch = "release-1.17"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  branch = "release-1.17"

[[constraint]]
  name = "k8s.io/cli-runtime"
  branch = "release-1.17"

[[constraint]]
  name = "k8s.io/kubectl"
  branch = "release-1.17"

[[constraint]]
  name = "github.com/bouk/monkey"
  version = "1.0.0"

# vendor/k8s.io/kubectl/pkg/util/term/resize.go:30:23: undefined: term.GetFdInfo
[[override]]
  name = "github.com/docker/docker"
  revision = "be7ac8be2ae072032a4005e8f232be3fc57e4127"

# vendor/k8s.io/kubectl/pkg/util/templates/markdown.go:66:11: undefined: blackfriday.LIST_ITEM_BEGINNING_OF_LIST
[[override]]
  name = "github.com/russross/blackfriday"
  version = "v1.5.2"

[[override]]
  name = "github.com/ghodss/yaml"
  branch = "master"
